### ISSUE TITLE
Is it possible to use the site with Markdown content instead of html?

### ISSUE THREAD

**Issue by hartzell** [mistic100/jekyll-bootstrap-doc#2]
I like the look and functionality of this tool but am hoping to be able to author content in markdown instead of HTML.

The only potential stumbling block I see is making the sections and heading have the right info to generate the menu on the right.

Before I flail around on my own I thought I'd ask for feedback about it.

Thanks!

**Comment by mistic100** [comment]
Unless mixing HTML and markdown I don't see how that would be possible.
We can't install custom gems on github pages thus we can't create a custom markdown parser

**Comment by hartzell** [comment]
ok, thanks.

**Comment by 0x30** [comment]
https://github.com/liubin-cm/liubin-cm.github.io

It seems OK, right? Forgive me for knowing nothing about the whole thing, so I can't do it. Can you come and have a look?

**Comment by mistic100** [comment]
Are you talking about the side menu ? It is generated from the blog posts (which is the primary usage of Jekyll), nothing comparable, it's not generated on the browser.

**Comment by 0x30** [comment]
Actually, I'm just looking for a documentation template, just like an bootstrap document.(http://v3.bootcss.com/getting-started/)..... So I found you. You can meet my needs, but it feels very troublesome to update...... Not as simple as markdown
