### ISSUE TITLE
Changelog page not working

### ISSUE THREAD

**Issue by jkeuper** [mistic100/jekyll-bootstrap-doc#5]
The changelog page does not work.

The API call does not give any result. The "releases" here are no real releases but partial releases. (Actual, they are tags.) You should create a real release on GH, so the changelog page actually shows something.

Compare https://github.com/WixEdit/WixEdit/releases and https://github.com/mistic100/jekyll-bootstrap-doc/releases.

And the api call: https://api.github.com/repos/WixEdit/WixEdit/releases and https://api.github.com/repos/mistic100/jekyll-bootstrap-doc/releases

--Jasper

**Comment by mistic100** [comment]
Ok did it.
Though I don't really care as long as the code is working in real usage.
